version: "3.7"
services:
  dev-db:
    container_name: tran-db
    image: postgres:14.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-postgres}
      POSTGRES_DB: ${POSTGRES_DB-postgres}
    ports:
      - "127.0.0.1:5432:5432"
    # volumes:
    #   - ./data.volume/postgres-dev/:/var/lib/postgresql/data/
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      test: ["CMD", "psql", "-U", "postgres", "-c", "SELECT 1"]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 5s
    # logging:
    #   driver: "syslog"
    #   options:
    #     syslog-tag: "postgres"
    #     syslog-address: "udp://localhost:514"


networks:
  backend: